# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-31 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20171221_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.FileField(null=True, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
